# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaMpAYuV5qinlMOXJYQJBqe_Ssf0tjG5
"""

# ===============================
# 🧠 EDA: Analisis Kepuasan Pelanggan
# ===============================

# Import library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

file_path = "jawaban.csv"


df = pd.read_csv(file_path, delimiter=';')
print(df.head())

df.columns = ["Timestamp", "Nama", "Alamat", "Kepuasan"]

# -------------------------------
# 2️⃣ Data Understanding
# -------------------------------
print("📋 Informasi Data:")
print(df.info())
print("\n🔍 5 Data Teratas:")
print(df.head())

print("\n📊 Statistik Deskriptif:")
print(df.describe(include='all'))

# -------------------------------
# 3️⃣ Data Cleaning
# -------------------------------
df["Kepuasan"] = df["Kepuasan"].str.strip().str.title()
df["Alamat"] = df["Alamat"].str.strip().str.title()

# Cek nilai unik
print("\nKategori Kepuasan:")
print(df["Kepuasan"].value_counts())

# -------------------------------
# 4️⃣ Analisis Deskriptif
# -------------------------------
# Frekuensi tiap kategori kepuasan
kepuasan_count = df["Kepuasan"].value_counts()
kepuasan_percent = round((kepuasan_count / len(df)) * 100, 2)

print("\n📈 Distribusi Kepuasan Pelanggan:")
print(pd.DataFrame({
    "Jumlah Responden": kepuasan_count,
    "Persentase (%)": kepuasan_percent
}))

# -------------------------------
# 5️⃣ Visualisasi
# -------------------------------
sns.set(style="whitegrid", palette="viridis")

# --- Grafik 1: Bar Chart Kepuasan Pelanggan ---
plt.figure(figsize=(8,5))
sns.countplot(x="Kepuasan", data=df, order=df["Kepuasan"].value_counts().index)
plt.title("Distribusi Kepuasan Pelanggan", fontsize=14)
plt.xlabel("Kategori Kepuasan")
plt.ylabel("Jumlah Responden")
plt.show()

# --- Grafik 2: Pie Chart Kepuasan Pelanggan ---
plt.figure(figsize=(6,6))
plt.pie(kepuasan_count, labels=kepuasan_count.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette("viridis"))
plt.title("Persentase Kepuasan Pelanggan")
plt.show()

# --- Grafik 3: Sebaran Domisili Pelanggan ---
plt.figure(figsize=(10,5))
sns.countplot(y="Alamat", data=df, order=df["Alamat"].value_counts().index)
plt.title("Sebaran Domisili Pelanggan", fontsize=14)
plt.xlabel("Jumlah Responden")
plt.ylabel("Alamat Domisili")
plt.show()

# --- Grafik 4: Jumlah Respon Berdasarkan Waktu ---
plt.figure(figsize=(8,4))
df["Tanggal"] = pd.to_datetime(df["Timestamp"]).dt.date
sns.countplot(x="Tanggal", data=df)
plt.title("Jumlah Respon Berdasarkan Tanggal Pengisian", fontsize=14)
plt.xlabel("Tanggal")
plt.ylabel("Jumlah Responden")
plt.xticks(rotation=45)
plt.show()

# -------------------------------
# 6️⃣ Insight & Kesimpulan
# -------------------------------
print("\n🧭 Insight Singkat:")
print("- Mayoritas responden menyatakan 'Sangat Memuaskan'.")
print("- Artinya tingkat kepuasan pelanggan terhadap pelayanan sangat tinggi.")
print("- Surabaya menjadi daerah asal pelanggan terbanyak (berdasarkan kolom Alamat).")
print("- Rata-rata pengisian survei terjadi pada awal hingga pertengahan Agustus 2025.")